# Generated by Django 2.0.4 on 2018-04-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30, unique=True)),
                ('vendor_name', models.CharField(max_length=30, unique=True)),
                ('img_src', models.CharField(max_length=255)),
                ('food_items', models.CharField(max_length=255)),
            ],
        ),
    ]
