# Generated by Django 2.0.4 on 2018-04-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0002_vendor_info_data_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_info',
            name='data_src',
        ),
    ]
