# Generated by Django 2.0.4 on 2018-04-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0004_vendor_food_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_food_stock',
            name='vendor_id',
            field=models.CharField(max_length=30),
        ),
    ]
