# Generated by Django 2.0.4 on 2018-04-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0006_auto_20180420_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_food_list',
        ),
    ]
