# Generated by Django 2.0.4 on 2018-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0007_delete_vendor_food_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_food_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('food_item', models.CharField(max_length=255)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
