# Generated by Django 2.0.4 on 2018-04-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0008_vendor_food_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_info',
            name='food_items',
        ),
    ]
