# Generated by Django 2.0.4 on 2018-04-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0009_remove_vendor_info_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_food_list',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
