# Generated by Django 2.0.4 on 2018-04-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0011_vendor_info_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_info',
            name='food_items',
        ),
    ]
