# Generated by Django 2.0.4 on 2018-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_pages', '0013_auto_20180421_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_food_list',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
