# Generated by Django 2.0.4 on 2018-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_db',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('item_list', models.CharField(max_length=30, unique=True)),
                ('grand_total', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
