# Generated by Django 2.0.4 on 2018-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_db',
            name='status',
            field=models.CharField(default='N/A', max_length=30, unique=True),
        ),
    ]
