# Generated by Django 2.0.4 on 2018-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20180427_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='grand_total',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order_db',
            name='item_list',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order_db',
            name='status',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
