# Generated by Django 2.0.4 on 2018-04-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_db_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_db',
            name='item_list',
            field=models.CharField(max_length=255),
        ),
    ]
